# makefile
# auther: richard
# time:   2013.10.6
include $(ROOTDIRS)/makefile.begin
CPPS = $(wildcard *.cpp)
OBJS = $(patsubst %.cpp, %.o, $(CPPS))

TARGET_DIRS =	\
		filter	\

include $(ROOTDIRS)/makefile.in
